version: "3"
services:
  app:
    image: nginx-php7.3-ideasoft:latest
    volumes:
      - .:/var/www/html
    links:
      - pgsql
    ports:
      - 8085:80
      - 443:443
  scheduler:
    image: nginx-php7.3-ideasoft:latest
    command: ./var/www/html/bin/run-scheduler.sh
    volumes:
      - .:/var/www/html
    links:
      - pgsql
  pgsql:
    image: postgres:10
    environment:
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_db     
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data           
    ports:
      - 5432:5433